In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:16pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

In [ ]:
a, b = 0, 1
n=10
while a< n:
    print(a,end=" ")
    a, b =b, a+b
print()

In [ ]:
a, b = 0 , 1
n=int(input("n값 미만까지 피보나치 수열 출력"))
lst=[0]
for i in range(0,n+1) :
    if n == a+b :
        lst.append(a)
    a, b = b, a+b
print(lst)    
        
## 0 , 1, 1,   2,        3,        5, 8, 11
#  a , b,a+b, a+b+b  a+b+b+a+b 

In [1]:
subject =('python','web', 'oracle','MySQL', 'DL', 'ML', 'LLM', 'flask/django')
"$".join(subject)

'python$web$oracle$MySQL$DL$ML$LLM$flask/django'

In [11]:
def concat(*subject, sep=" "):
    return sep.join(subject)
subject

('python', 'web', 'oracle', 'MySQL', 'DL', 'ML', 'LLM', 'flask/django')

In [14]:
concat('python','web', 'oracle','MySQL', 'DL', 'ML', 'LLM', 'flask/django','@@@')

'python web oracle MySQL DL ML LLM flask/django @@@'

In [8]:
class Person :
    academy = "MBC" #클래스변수
    def __init__(self,name,gender) :
        self.name = name
        self.gender = gender
        print('Person 객체 생성합니다')
    def __str__(self):
        return f"{self.name}은 {self.gender}이죠"
        

In [9]:
p1 = Person('홍길동','남자')
print(p1)

Person 객체 생성합니다
홍길동은 남자이죠


In [10]:
isinstance(p1,Person)

True

In [1]:
#연습문제1
class Shape:
    def __init__(self, x=0, y=0):
        self.x=x
        self.y=y
    def move(self,x,y):
        self.x=x
        self.y=y        
    def __str__(self):
        return "x좌표값 : {}, y좌표값 : {}".format(self.x, self.y)
    @staticmethod
    def print_static_method():
        print('static 메소드 : x,y좌표값 구현')
        
        
class Triangle(Shape) :
    __count = 0
    def __init__(self, width, height, x, y) :
        self.width = width
        self.height = height
        super().__init__(x, y)
        Triangle._Triangle__count += 1
    def __del__(self) :
        Triangle._Triangle__count -= 1     
    def calc_area(self) :
        print(f"삼각형 면적은 {self.width*self.height*0.5}입니다.")
    def __str__(self) :
        return super().__str__()+f"  삼각형 면적은 {self.width*self.height*0.5}입니다."
    @classmethod
    def get_count(cls):
        return cls.__count

In [2]:
s1=Shape()
print(s1.__str__())
Shape.print_static_method()

x좌표값 : 0, y좌표값 : 0
static 메소드 : x,y좌표값 구현


In [3]:
t1=Triangle(4,3,0,10)
t2=Triangle(3,4,5,5)
print('Triangle객체 갯수 :', Triangle.get_count())

Triangle객체 갯수 : 2


In [4]:
print(t1)

x좌표값 : 0, y좌표값 : 10  삼각형 면적은 6.0입니다.


In [5]:
print(t2)

x좌표값 : 5, y좌표값 : 5  삼각형 면적은 6.0입니다.


In [4]:
t1.move(50,50)
print(t1)

x좌표값 : 50, y좌표값 : 50  삼각형 면적은 6.0입니다.


In [7]:
class Person :
    academy = "MBC"
    def __init__(self, name, gender):
        self.name=name
        self.gender=gender
        print('Person 객체를 생성합니다')
    def print_info(self):
        print("{}의 {}는 {}입니다".format(self.academy, self.name, self.gender))
p1=Person('홍길동',"남자")
p1.print_info()
p1.academy = "딴데"
p1.print_info()


Person 객체를 생성합니다
MBC의 홍길동는 남자입니다
딴데의 홍길동는 남자입니다


In [8]:
isinstance(p1,Person)

True

In [6]:
with open('data/ch09.txt','a',encoding='utf-8',newline="") as f : 
    f.write('Python is easy.\nPython is smart.\n')

In [11]:
with open('data/ch09.txt', 'a', encoding='utf-8') as f :
    text_list= ['writelines\n']
#     for line in text_list :
#         f.write(line)
    f.writelines(text_list)
        

In [15]:
with open('data/ch09_customers.txt','r',encoding='utf-8') as txtfile :
    while line!= "":
        print(line, end="")
        line=txtfile.readline()
    

  홍길동	010-9999-9999	k@hong.com     	             30	  5	vvip
  홍길동	010-9999-9999	k@hong.com     	             30	  5	vvip
  유길동	010-5432-2222	y@hong.com     	             20	  2	가칠해
  신림동	010-8888-8888	s@song.com     	             33	  3	글쎄
  홍길동	010-7777-7777	h@hong.com     	             33	  4	vip
  정성용	010-2222-2222	s@naver.com    	             23	  5	해당사항없음


In [14]:
print(line[2])

홍


In [ ]:
with open('data/ch09_member.txt','r',encoding='utf=8') as f :
    lines =f.readlines()
for line in lines:
    #print(line, end="")
    data=line.strip().split(',')  #.strip() \n 같은걸 빼주는 역할
    name=data[0].strip()
    age=int(data[1].strip())
    email=data[2].strip()
    address=data[3].strip()
    print(f"이름:{name}, 나이:{age}, 메일:{email}, 주소:{address}")

In [2]:
class Member:
    def __init__(self,name,age,email,address):
        self.name =name
        self.age =age
        self.email =email
        self.address =address
    def __str__(self):
        return "{},{},{},{}".format(self.name,
                                    self.age,
                                    self.email,
                                    self.address)
    def __eq__(self, other):
        if isinstance(other, Member):
            return self.__str__() == other.__str__()
        return False
    def as_dict(self):   #객체를 딕셔너리로 return
        return {'name':self.name, 'age':self.age, 'email':self.email, 'address':self.address}
    def as_list(self): #객체를 리스트로 return
        return [self.name, self.age, self.email, self.address]
        

In [3]:
member = Member("홍길동",33,"hong@h.co.kr","신림동")
print(member)

홍길동,33,hong@h.co.kr,신림동


In [5]:
member.as_list()

['홍길동', 33, 'hong@h.co.kr', '신림동']

In [8]:
member_list=[]
member_dict_list=[]
with open('data/ch09_member.txt','r',encoding='utf=8') as f :
    lines =f.readlines()
for line in lines:
    #print(line, end="")
    data=line.strip().split(', ')  #.strip() \n 같은걸 빼주는 역할
    name=data[0]
    age=int(data[1])
    email=data[2]
    address=data[3]
    member=Member(name, age, email, address)    
    member_list.append(member)
    member_dict_list.append(member.__dict__)

In [12]:
print(member_list)

[<__main__.Member object at 0x000002381EDEEE00>, <__main__.Member object at 0x000002381EDEEAA0>, <__main__.Member object at 0x000002381EDEC640>]


In [13]:
import csv
with open('data/ch09_member1.csv','r',encoding='utf-8') as f : 
    reader = csv.reader(f)
    for row in reader : 
        print(row
            )

['홍길동', '20', 'kildong@hong.com', '서울시 관악구']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구']
['신길동', '30', 'sindong@hong.com', '서울시 동작구']


In [ ]:
with open('data/ch09_member1-cp.csv') as f : 
    reader = csv.reader(f)  # 보조 빨대
    result = list

In [ ]:
with open('data/ch09_member2-write-cp.csv','a', newline="") as f :
    writer =csv.writer(f)
    writer.writerrows

In [73]:
class Customer :
    def __init__(self, name, phone, email, age, grade, etc):
        self.name = name
        self.phone = phone
        self.email = email
        self.age = age
        self.grade = grade
        self.etc = etc        
    def as_dict(self):
        return self.__dict__
    def __str__(self):                                                    #화면 출력용
        return "{:>5}\t{:3}\t{:15}\t{:15}\t{:3}\t{}".format(self.grade*"*",
                                                    self.name,
                                                    self.phone,
                                                    self.email,
                                                    self.age,
                                                    self.etc)
    def to_txt_style(self):
        return "{:>5}\t{:3}\t{:15}\t{:15}\t{:3}\t{}".format(self.name,
                                                    self.phone,
                                                    self.email,
                                                    self.age,
                                                    self.grade,
                                                    self.etc)

In [78]:
c1=Customer("홍길동","010-1234-1234","h@h.com", 30, 4, "기타")
print(c1.as_dict())


{'name': '홍길동', 'phone': '010-1234-1234', 'email': 'h@h.com', 'age': 30, 'grade': 4, 'etc': '기타'}


In [79]:
print(c1)

 ****	홍길동	010-1234-1234  	h@h.com        	 30	기타


In [80]:
def to_customer(row):
    data = row.strip(),split(', ')
    name = data[0]
    phone = data[1]
    email = data[2]
    age   = int(data[3])
    grade = int(data[4])
    etc   = data[5]
    return Customer(name, phone, email, age, grade, etc)    

In [94]:
def load_customer():
    customer_list=[]
    try:
        with open('data/ch09_customers.txt','r', encoding='utf-8') as f :
            lines=f.readlines
            for line in lines :
                customer = to_customer(line)
                customer_list.append(customer)
    except:
        return customer_list



[]


In [91]:
def load_customers():
    customer_list = []
    #파일에 입력받은 customer 정보를 append
    try:
        with open('data/ch09_customers.txt','r', encoding='utf-8') as f :
            lines=f.readlines()
            for line in lines:
                customer = to_customer(line)
                customer_list.append(customer)
    except:
        print('데이터 파일 ch09_customers.txt가 없어서 초기화했습니다')
        with open('data/ch09_customers.txt','w', encoding='utf-8') as f : 
            f.write('')
    return customer_list

In [92]:
customer_list = load_customer()

데이터 파일 ch09_customers.txt가 없어서 초기화했습니다


In [5]:
import numpy as np
a=np.arange(15)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(15,)


In [10]:
from numpy import arange
a = arange(15,dtype=np.int32).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.itemsize

4

In [14]:
a.shape=(5,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a.shape=(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
a.dtype
a=a.astype(np.int64)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int64)

In [29]:
a=a.astype(np.float64)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [31]:
a.ravel().astype(np.int64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [34]:
a=a.ravel().astype(np.int64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [35]:
%%time

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [37]:
%time

CPU times: total: 0 ns
Wall time: 0 ns


In [38]:
import pickle
with open('data/ch10.pk2','wb') as f :
    pickle.dump(a,f)

In [43]:
with open('data/ch10.pk2','rb') as f : 
    loaded_a=pickle.load(f)
loaded_a.reshape(3,4)
loaded_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [46]:
b=loaded_a.astype(np.int32)
b.dtype

dtype('int32')

In [47]:
a=np.array([2, 14, 6])   #기본으로 dtype=np.int32  실수의 기본타입은 float64
a

array([ 2, 14,  6])

In [53]:
for item in a :
    print(item, end ='\s')

2\s14\s6\s

In [54]:
b=np.array([[1.5,2.3],[4,5]])
b.dtype

dtype('float64')

In [57]:
a= np.array([[1.5, 2.3],
            [4,5]],dtype=np.float32).reshape(1,4) 

In [58]:
l = [[1.5, 2.3],[4,5]]
for row in l:
    for item in row:
        print(item, end=" ")

1.5 2.3 4 5 

In [62]:
a.shape=(2,2)
for i, row in enumerate(a):
    for j, item in enumerate(row):
#         print(f"{i}행{j}열 : {l[i][j]}", end='\t') #float16은 소숫점이하가 불안정
          print(f"{i}행{j}열 : {a[i,j]}", end='\t')
    print()

0행0열 : 1.5	0행1열 : 2.299999952316284	
1행0열 : 4.0	1행1열 : 5.0	


In [64]:
c=np.array([[1,2],[3,4]],dtype=np.uint8)

In [65]:
d=np.array(c,copy=True)

In [67]:
d[0,0]=100

In [68]:
d

array([[100,   2],
       [  3,   4]], dtype=uint8)

In [69]:
c

array([[1, 2],
       [3, 4]], dtype=uint8)

In [ ]:
np.zeros
np.ones
np.full()

In [3]:
import pandas as pd

In [5]:
member=pd.read_csv('data/ch11_member.csv')
member

,Name,Age,Email,Address,Birth
0,홍길동,20,hong@hong.com,서울시 강동구,1999-01-01
1,홍길서,30,seo@hong.com,서울시 중구,1999-12-01
2,홍길남,21,nam@hong.com,서울시 강동구,1999-11-01
3,홍길북,22,buk@hong.com,서울시 관악구,1999-05-01
4,홍길중,23,mid@hong.com,부산시 중구,1999-01-30
5,#홍길뜽,24,non@not.com,없는구,2000-01-01


In [6]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [8]:
member['Age']=member['Age'].astype('str')
member['Age']

0    20
1    30
2    21
3    22
4    23
5    24
Name: Age, dtype: object

In [9]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      object
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: object(5)
memory usage: 368.0+ bytes


In [11]:
member.loc[0,'Age']

'20'

In [12]:
member['Age'].astype('int32')

0    20
1    30
2    21
3    22
4    23
5    24
Name: Age, dtype: int32

In [15]:
import numpy as np
member['Age'].astype(np.int16)

0    20
1    30
2    21
3    22
4    23
5    24
Name: Age, dtype: int16

In [23]:
member['Age']=pd.to_numeric(member['Age'], downcast='integer',errors='coerce')
member['Age']

0    20
1    30
2    21
3    22
4    23
5    24
Name: Age, dtype: int8

In [36]:
member.loc[0,"Birth"]

Timestamp('1999-01-01 00:00:00')

In [34]:
member=member.astype({"Birth":"datetime64[ns]","Age":"int16"})
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     6 non-null      object        
 1   Age      6 non-null      int16         
 2   Email    6 non-null      object        
 3   Address  6 non-null      object        
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int16(1), object(3)
memory usage: 332.0+ bytes


In [40]:
member['Birth']=pd.to_datetime(member['Birth'], format="%Y@%m@%d")
member.loc[0,"Birth"]

Timestamp('1999-01-01 00:00:00')

In [42]:
member.Birth.dt.year

0    1999
1    1999
2    1999
3    1999
4    1999
5    2000
Name: Birth, dtype: int64

In [48]:
import seaborn as sns 
iris=sns.load_dataset('iris')
iris.columns=[col.replace('_','').capitalize() for col in iris.columns]
iris

,Sepallength,Sepalwidth,Petallength,Petalwidth,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [50]:
iris.to_csv('data/ch11_test.iris.zip',
           sep='\t',
           encoding='utf-8',
           index=False,
           compression='infer')


In [ ]:
from statsmodels.api import datasets

In [52]:
import pandas as pd 
pd.__version__

'1.5.3'

In [54]:
member4=pd.read_csv('data/ch09_member4.csv')
member4

,name,age,email,address,job
0,홍길동,20,h@h.com,서울시 관악구,없음
1,신길동,40,s@h.com,서울시 영등포구,팀장
2,김길동,30,k@h.com,서울시 동작구,없음


In [55]:
member1=pd.read_csv('data/ch09_member1.csv')  
member1

,홍길동,20,kildong@hong.com,서울시 관악구
0,김길동,40,kimdong@hong.com,서울시 영등포구
1,신길동,30,sindong@hong.com,서울시 동작구


In [60]:
member1=pd.read_csv('data/ch09_member1.csv',names=['name','age','email',"addrerss"])  
member1

,name,age,email,addrerss
0,홍길동,20,kildong@hong.com,서울시 관악구
1,김길동,40,kimdong@hong.com,서울시 영등포구
2,신길동,30,sindong@hong.com,서울시 동작구


In [62]:
member1=pd.read_csv('data/ch09_member1.csv',header=None,names=['name','age','email',"addrerss"])
member1

,name,age,email,addrerss
0,홍길동,20,kildong@hong.com,서울시 관악구
1,김길동,40,kimdong@hong.com,서울시 영등포구
2,신길동,30,sindong@hong.com,서울시 동작구


In [63]:
d = {'kor':[100,90],'mat':[95,99]}
d

{'kor': [100, 90], 'mat': [95, 99]}

In [66]:
df=pd.DataFrame(d)
df

,kor,mat
0,100,95
1,90,99


In [67]:
df.to_dict()

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [68]:
df.to_numpy()

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [69]:
d = [{'kor':100, 'mat':95.0},
     {'kor':90, 'mat': 99}]
df=pd.DataFrame(d) # 데이터 프레임의 열은 동일 자료형
df

,kor,mat
0,100,95.0
1,90,99.0


In [72]:
df.dtypes

kor      int64
mat    float64
dtype: object

In [73]:
df['kor']

0    100
1     90
Name: kor, dtype: int64

In [74]:
df.kor

0    100
1     90
Name: kor, dtype: int64

In [75]:
d = [{'kor':100, 'mat':100},
     {'kor':90, 'mat':99},
     {'kor':83, 'eng':85}]

In [77]:
df=pd.DataFrame(d)
df

,kor,mat,eng
0,100,100.0,NaN
1,90,99.0,NaN
2,83,NaN,85.0


In [85]:
df['eng'][2]

85.0

In [86]:
type(np.nan)

float

In [88]:
kor = [100, 90, 80, 70, 60]
mat = [90, 80, 81, 71, 61]
df=pd.DataFrame({'kor':kor,"mat":mat})
df

,kor,mat
0,100,90
1,90,80
2,80,81
3,70,71
4,60,61


In [93]:
b=np.c_[kor,mat]
b

array([[100,  90],
       [ 90,  80],
       [ 80,  81],
       [ 70,  71],
       [ 60,  61]])

In [92]:
pd.DataFrame(b,columns=['kor','mat'])

,kor,mat
0,100,90
1,90,80
2,80,81
3,70,71
4,60,61


In [95]:
l = [[100,90],
     [70,80]]
l

[[100, 90], [70, 80]]

In [99]:
member = pd.read_csv('data/ch11_membercp949.csv',
                     encoding='cp949',
                     nrows=2) 
member

,Name,Age,Email,Address,Birth
0,홍길동,20,hong@hong.com,서울시 강동구,1999-01-01
1,홍길서,30,seo@hong.com,서울시 중구,1999-12-01


In [101]:
member = pd.read_csv('data/ch11_member.csv',comment="#",parse_dates=['Birth'])
member

,Name,Age,Email,Address,Birth
0,홍길동,20,hong@hong.com,서울시 강동구,1999-01-01
1,홍길서,30,seo@hong.com,서울시 중구,1999-12-01
2,홍길남,21,nam@hong.com,서울시 강동구,1999-11-01
3,홍길북,22,buk@hong.com,서울시 관악구,1999-05-01
4,홍길중,23,mid@hong.com,부산시 중구,1999-01-30


In [102]:
member.columns 

Index(['Name', 'Age', 'Email', 'Address', 'Birth'], dtype='object')

In [103]:
member.columns= ['이름','나이','메일','주소','생년월일']
member

,이름,나이,메일,주소,생년월일
0,홍길동,20,hong@hong.com,서울시 강동구,1999-01-01
1,홍길서,30,seo@hong.com,서울시 중구,1999-12-01
2,홍길남,21,nam@hong.com,서울시 강동구,1999-11-01
3,홍길북,22,buk@hong.com,서울시 관악구,1999-05-01
4,홍길중,23,mid@hong.com,부산시 중구,1999-01-30


In [104]:
member.index

RangeIndex(start=0, stop=5, step=1)