In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:95% !important;}
div.cell.code_cell.rendered{width:95%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
.inner_cell{font-size:20pt;}
div.text_cell_render pre code {font-size:20pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

# 1. tensorflow v2.xx에서 v1 사용하기

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() #tensorflow v2 비활성화하고 v1만 활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## Tensorflow
- 데이터 흐름 그래프(tensor 흐름을 나타내는 설계도)
- 그래프는 node와 edge로 구성
- sess= tf.Session()을 이용하여 실행환경
- sess.run()을 통해서 실행결과를 확인

In [9]:
# 1. tensor(상수node, 변수node, 연산node) 정의
node1 = tf.constant('Hello, Tensorflow')
# 2. 세션 생성
sess=tf.Session()
# 3. 실행 
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, Tensorflow'
Hello, Tensorflow


In [12]:
#간단한 연산 tensor 그래프
# 1. 그래프 정의
node1= tf.constant(10, dtype=tf.float16)
node2= tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1,node2)
# 2. 세션 생성
sess= tf.Session()
# 3. 세션 실행 및 결과
n1, n2, n3 = sess.run([node1,node2,node3])
print(n1, n2, n3)

10.0 20.0 30.0


In [14]:
# 타입 변경
node1 = tf.constant(np.array([10,20,30]),dtype=tf.int16)
node2 = tf.cast(node1,dtype=tf.float16)
sess= tf.Session()
print(sess.run([node1,node2]))

[array([10, 20, 30], dtype=int16), array([10., 20., 30.], dtype=float16)]


In [18]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2,3,4])
m= tf.reduce_mean(data)
sess=tf.Session()
sess.run(m)

2.5

In [66]:
#tf.random_normal([shape]): 평균난수 발생
w= tf.random.normal([1])
sess=tf.Session()
sess.run(w)

array([0.08722091], dtype=float32)

In [ ]:
#변수노드
w=tf.Variable(tf.random.normal([1,3]))
sess=tf.Session()
sess.run(tf.global_variables_initializer()) #난수가 발생될 변수 초기화
sess.run(w)

# 2. tensorflow v1을 이용한 회귀분석 구현
## 2.1 독립변수 x가 1개, 타겟변수 y가 1개

In [78]:
# tensor 그래프 정의
# 데이터셋 확보
x=np.array([1,2,3])
y=np.array([2,3,4])
# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
# hat,hypothesis :  결과는 numpy 배열
H = w * x + b
# cost function (손실함수 : mse) : H-y의 제곱의 평균
cost= tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는 것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향 학습(경사하강법:GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
#w와 b 값 초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서 fit함수)
for step in range(1,5001):
    _, cost_val,w_val,b_val = sess.run([train, cost, w, b])
    if step%300==1:
        print(f'{step}번째 cost:{cost_val}, w:{w_val}, b:{b_val}')

1번째 cost:7.118560791015625, w:[0.38635692], b:[-0.09432626]
301번째 cost:0.016227517277002335, w:[1.1475967], b:[0.6644779]
601번째 cost:0.0038290165830403566, w:[1.071696], b:[0.8370183]
901번째 cost:0.000903502746950835, w:[1.0348269], b:[0.92083025]
1201번째 cost:0.00021318782819435, w:[1.0169173], b:[0.96154284]
1501번째 cost:5.0303660827921703e-05, w:[1.0082177], b:[0.9813193]
1801번째 cost:1.1869403351738583e-05, w:[1.0039918], b:[0.9909257]
2101번째 cost:2.8015726911689853e-06, w:[1.0019394], b:[0.99559146]
2401번째 cost:6.61592991946236e-07, w:[1.0009427], b:[0.99785763]
2701번째 cost:1.565473581877086e-07, w:[1.0004586], b:[0.99895793]
3001번째 cost:3.71605040072609e-08, w:[1.0002234], b:[0.9994923]
3301번째 cost:8.87171847097079e-09, w:[1.0001094], b:[0.99975204]
3601번째 cost:2.1476995737401694e-09, w:[1.0000541], b:[0.99987805]
3901번째 cost:5.004778813599842e-10, w:[1.0000259], b:[0.9999411]
4201번째 cost:1.430559420922961e-10, w:[1.0000141], b:[0.9999686]
4501번째 cost:5.328478283606053e-11, w:[1.0000

In [79]:
w_, b_ =sess.run([w[0],b[0]])
w_, b_

(1.0000087, 0.9999811)

In [80]:
def predict(x):
    return x*w_+b_

In [81]:
predict(5)

6.000024616718292

## 2.2 predict를 위한 placeholder이용
- placeholder : 외부에서 데이터를 입력받을 수 있는 노드

In [84]:
x = tf.placeholder(dtype=tf.float32)
H = w_* x + b_
sess = tf.Session()
sess.run([H,x],{x:2.5})

[3.5000029, array(2.5, dtype=float32)]

In [86]:
sess.run(H,{x:np.array([2.5,3,3.5])})

array([3.5000029, 4.000007 , 4.5000114], dtype=float32)

In [87]:
# tensor 그래프 정의
# 데이터셋 확보
x_data=np.array([1,2,3])
y_data=np.array([2,3,4])
# placeholder 노드 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
# hat,hypothesis :  결과는 numpy 배열
H = w * x + b
# cost function (손실함수 : mse) : H-y의 제곱의 평균
cost= tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는 것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향 학습(경사하강법:GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
#w와 b 값 초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서 fit함수)
for step in range(1,5001):
    _, cost_val,w_val,b_val = sess.run([train, cost, w, b],
                                      feed_dict={x:x_data,y:y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val}, w:{w_val}, b:{b_val}')

1번째 cost:0.07527679204940796, w:[1.1121923], b:[0.5378513]
301번째 cost:0.006247250828891993, w:[1.0915787], b:[0.7918199]
601번째 cost:0.0014740921324118972, w:[1.0444851], b:[0.898875]
901번째 cost:0.0003478317230474204, w:[1.0216091], b:[0.95087767]
1201번째 cost:8.20747300167568e-05, w:[1.0104969], b:[0.9761383]
1501번째 cost:1.9367011191206984e-05, w:[1.0050989], b:[0.9884089]
1801번째 cost:4.5696374399994966e-06, w:[1.0024769], b:[0.99436945]
2101번째 cost:1.0788306781250867e-06, w:[1.0012035], b:[0.9972643]
2401번째 cost:2.5515979018564394e-07, w:[1.0005854], b:[0.99866974]
2701번째 cost:6.052807322021181e-08, w:[1.000285], b:[0.9993521]
3001번째 cost:1.4422051997087237e-08, w:[1.0001391], b:[0.99968356]
3301번째 cost:3.4446732133375235e-09, w:[1.0000681], b:[0.99984545]
3601번째 cost:8.302976084451075e-10, w:[1.0000331], b:[0.9999241]
3901번째 cost:2.0012673462854735e-10, w:[1.0000167], b:[0.99996257]
4201번째 cost:5.66349918351694e-11, w:[1.000009], b:[0.9999804]
4501번째 cost:5.195962063386794e-11, w:[1.0

In [88]:
# 예측하기 
sess.run(H, feed_dict={x:2.5})

array([3.5000029], dtype=float32)

In [91]:
sess.run(H, feed_dict={x:np.array([2.5,3.5])})

array([3.5000029, 4.5000114], dtype=float32)

## 2.3 scale이 다른 데이터들의 회기분석(scale 조정x)

In [102]:
# tensor 그래프 정의
# 데이터셋 확보
x_data=np.array([1,2,5,8,10])
y_data=np.array([5,15,68,80,95])
# placeholder 노드 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
# hat,hypothesis :  결과는 numpy 배열
H = w * x + b
# cost function (손실함수 : mse) : H-y의 제곱의 평균
cost= tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는 것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향 학습(경사하강법:GradientDescent)
'''
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
#train =optimizer.minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
#세션 생성
sess = tf.Session()
#w와 b 값 초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서 fit함수)
for step in range(1,3001):
    _, cost_val,w_val,b_val = sess.run([train, cost, w, b],
                                      feed_dict={x:x_data,y:y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val}')
print(f'{step}번째 cost:{cost_val}')        

1번째 cost:4456.501953125
301번째 cost:79.5806655883789
601번째 cost:79.4480972290039
901번째 cost:79.3553695678711
1201번째 cost:79.29051971435547
1501번째 cost:79.2451171875
1801번째 cost:79.21336364746094
2101번째 cost:79.1911849975586
2401번째 cost:79.1756362915039
2701번째 cost:79.16477966308594
3000번째 cost:79.15718078613281


## 2.4 scale이 다른 데이터의 회귀분석(scale조정 O)
### scale 조정방법 : 모든 데이터를 일정범위내로 조정
- normalization(정규화) : 모든 데이터를 0~1사이로 조정
   
                           X - Xmin
    normalization  =  ─────────────────
                          Xmax -Xmin
        *위의 식보다 라이브러리 추천(sklearn.preprocessing.MinMaxScaler)
- standardization(표준화) : 데이터의 평균을 0, 표준편차를 1로 조정

                          X - Xmean
    standardization = ─────────────────
                        Xstd(표준편차)
        *위의 식보다 라이브러리 추천(sklearn.preprocessing.standardScaler)
        
        
        

In [103]:
x_data

array([ 1,  2,  5,  8, 10])

In [107]:
#라이브러리를 쓰지 않고 정규화
x_data=np.array([1,2,5,8,10])
y_data=np.array([5,15,68,80,95])
norm_scaled_x_data= (x_data -x_data.min()) /(x_data.max()-x_data.min()) 
print(norm_scaled_x_data)
norm_scaled_y_data= (y_data -y_data.min()) /(y_data.max()-y_data.min()) 
print(norm_scaled_y_data)

[0.         0.11111111 0.44444444 0.77777778 1.        ]
[0.         0.11111111 0.7        0.83333333 1.        ]


In [111]:
#라이브러리를 사용하여 정규화
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
x_data=np.array([1,2,5,8,10]).reshape(-1,1)
y_data=np.array([5,15,68,80,95]).reshape(-1,1)
scaler_x=MinMaxScaler()  # x_data를 변환시킬 객체만들기
scaler_x.fit(x_data)
norm_scaled_x_data=scaler_x.transform(x_data)
print(norm_scaled_x_data)

scaler_y=MinMaxScaler() # y_data를 변환시킬 객체만들기
norm_scaled_y_data=scaler_y.fit_transform(y_data)
print(norm_scaled_y_data)
np.column_stack([x_data,norm_scaled_x_data,y_data,norm_scaled_y_data])

[[0.        ]
 [0.11111111]
 [0.44444444]
 [0.77777778]
 [1.        ]]
[[0.        ]
 [0.11111111]
 [0.7       ]
 [0.83333333]
 [1.        ]]


array([[ 1.        ,  0.        ,  5.        ,  0.        ],
       [ 2.        ,  0.11111111, 15.        ,  0.11111111],
       [ 5.        ,  0.44444444, 68.        ,  0.7       ],
       [ 8.        ,  0.77777778, 80.        ,  0.83333333],
       [10.        ,  1.        , 95.        ,  1.        ]])

In [117]:
#라이브러리를 쓰지 않고 표준화
x_data=np.array([1,2,5,8,10])
y_data=np.array([5,15,68,80,95])
stan_scaled_x_data= (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data= (y_data - y_data.mean()) / y_data.std()
print(np.column_stack([x_data,stan_scaled_x_data,norm_scaled_x_data]))
print()
print(np.column_stack([y_data,stan_scaled_y_data,norm_scaled_y_data]))

[[ 1.         -1.22474487  0.        ]
 [ 2.         -0.93313895  0.11111111]
 [ 5.         -0.05832118  0.44444444]
 [ 8.          0.81649658  0.77777778]
 [10.          1.39970842  1.        ]]

[[ 5.         -1.32373476  0.        ]
 [15.         -1.04563922  0.11111111]
 [68.          0.42826713  0.7       ]
 [80.          0.76198177  0.83333333]
 [95.          1.17912508  1.        ]]


In [119]:
# 라이브러리를 사용하여 표준화
x_data=np.array([1,2,5,8,10]).reshape(-1,1)
y_data=np.array([5,15,68,80,95]).reshape(-1,1)
scaler_x= StandardScaler()
stan_scaled_x_data = scaler_x.fit_transform(x_data)

scaler_y= StandardScaler()
stan_scaled_y_data = scaler_y.fit_transform(y_data)
print(np.column_stack([stan_scaled_x_data,stan_scaled_y_data]))

[[-1.22474487 -1.32373476]
 [-0.93313895 -1.04563922]
 [-0.05832118  0.42826713]
 [ 0.81649658  0.76198177]
 [ 1.39970842  1.17912508]]


In [120]:
# 스케일 조정된 데이터를 다시 복구 : invers_transform() 이용
scaler_x.inverse_transform(stan_scaled_x_data)

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 8.],
       [10.]])

In [121]:
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [125]:
# placeholder 노드 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
# hat,hypothesis :  결과는 numpy 배열
H = w * x + b
# cost function (손실함수 : mse) : H-y의 제곱의 평균
cost= tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는 것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향 학습(경사하강법:GradientDescent)
'''
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
#train =optimizer.minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
#세션 생성
sess = tf.Session()
#w와 b 값 초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서 fit함수)
for step in range(1,3001):
    _, cost_val,w_val,b_val = sess.run([train, cost, w, b],
                                      feed_dict={x:norm_scaled_x_data,
                                                 y:norm_scaled_y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val}')
print(f'{step}번째 cost:{cost_val}')       

1번째 cost:1.0077656507492065
301번째 cost:0.03454852104187012
601번째 cost:0.015884514898061752
901번째 cost:0.01127903163433075
1201번째 cost:0.010142600163817406
1501번째 cost:0.009862172417342663
1801번째 cost:0.009792972356081009
2101번째 cost:0.009775898419320583
2401번째 cost:0.009771682322025299
2701번째 cost:0.009770642034709454
3000번째 cost:0.009770384058356285


## 2.5 독립변수 x가 3개, 타겟변수 y가 1개인 회귀분석
- 25page

In [30]:
# dataset
X_data= np.array([[73,80,75], # 학습시에는 X에 5행3열 / 예측시 ?행3열
                 [93,88,93],
                 [89,91,90],
                 [96,98,100],
                 [73,66,70]])
y_data= np.array([[152],     # 학습시에는 y에 5행1열 / 예측시 ?행1열
                 [185],
                 [180],
                 [196],
                 [142]])
X=tf.placeholder(shape=[None,3],dtype=tf.float32)
y=tf.placeholder(shape=[None,1],dtype=tf.float32)
#w&b
W=tf.Variable(tf.random.normal([3,1]))
b=tf.Variable(tf.random.normal([1]))
# 예측값
H = X @ W + b # @행렬곱(tf.matmul()행렬곱)
H= tf.matmul(X,W) + b
# 손실함수(loss) : mse -> cost
cost = tf.reduce_mean(tf.square(H-y))
#optimizer & train
train = tf.train.GradientDescentOptimizer(learning_rate=0.00004).minimize(cost)
#sess생성 & variable 초기화
sess=tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(60001):
    cost_val = sess.run([train, cost], feed_dict={X:X_data, y:y_data})
    if step%300==1:
        print(f'{step}번째 cost: {cost_val}')
print(f'{step}번째 cost: {cost_val}')    


1번째 cost: [None, 6295.854]
301번째 cost: [None, 2.3668296]
601번째 cost: [None, 1.4096293]
901번째 cost: [None, 0.9052175]
1201번째 cost: [None, 0.6373309]
1501번째 cost: [None, 0.49310026]
1801번째 cost: [None, 0.41362658]
2101번째 cost: [None, 0.36818904]
2401번째 cost: [None, 0.34072188]
2701번째 cost: [None, 0.32285196]
3001번째 cost: [None, 0.3101833]
3301번째 cost: [None, 0.3004176]
3601번째 cost: [None, 0.29235044]
3901번째 cost: [None, 0.28533]
4201번째 cost: [None, 0.27901232]
4501번째 cost: [None, 0.27321535]
4801번째 cost: [None, 0.26783362]
5101번째 cost: [None, 0.2627972]
5401번째 cost: [None, 0.25807697]
5701번째 cost: [None, 0.2536246]
6001번째 cost: [None, 0.24943061]
6301번째 cost: [None, 0.24547902]
6601번째 cost: [None, 0.24174854]
6901번째 cost: [None, 0.2382369]
7201번째 cost: [None, 0.23491862]
7501번째 cost: [None, 0.23178598]
7801번째 cost: [None, 0.22883411]
8101번째 cost: [None, 0.22604811]
8401번째 cost: [None, 0.22341779]
8701번째 cost: [None, 0.2209274]
9001번째 cost: [None, 0.21858445]
9301번째 cost: [None, 0.2163827

In [35]:
#예측
input_data = np.array([[72,79,74],
                      [99,98,82]])
input_data[0]

array([72, 79, 74])

In [32]:
sess.run(H,feed_dict={X:input_data})

array([[149.49481],
       [192.01117]], dtype=float32)

In [36]:
sess.run(H,feed_dict={X:[input_data[0]]})

array([[149.49481]], dtype=float32)

## scale 조정 후 학습하고 예측하기


In [61]:
from sklearn.preprocessing import StandardScaler
X_data = np.array([[73,80,75],   # 학습시에는 X에 5행3열 / 예측시에는 ?행3열
                   [93,88,93],
                   [89,91,90],
                   [96,98,100],
                   [73,66,70]])
y_data = np.array([[152],      # 학습시에는 y에 5행1열 / 예측시에는 ?행1열
                   [185],
                   [180],
                   [196],
                   [142]])
scaler_x = StandardScaler()
scaler_y = StandardScaler()
scaled_X_data = scaler_x.fit_transform(X_data)
scaled_y_data = scaler_y.fit_transform(y_data)
np.column_stack([scaled_X_data, scaled_y_data])

array([[-1.19344226, -0.42020085, -0.93897274, -0.92622337],
       [ 0.82934123,  0.31058324,  0.65550927,  0.68248038],
       [ 0.42478453,  0.58462728,  0.38976227,  0.43873739],
       [ 1.13275875,  1.22406336,  1.27558561,  1.21871496],
       [-1.19344226, -1.69907302, -1.38188441, -1.41370936]])

In [62]:
X = tf.placeholder(shape=[None, 3], dtype=tf.float32)
y = tf.placeholder(shape=[None, 1], dtype=tf.float32)
# w & b
W = tf.Variable(tf.random.normal([3, 1]))
b = tf.Variable(tf.random.normal([1]))
# 예측값
# H = X @ W + b # @, tf.matmul() 행렬곱
H = tf.matmul(X, W) + b
# 손실함수(loss) : mse
cost = tf.reduce_mean(tf.square(H - y))
# optimizer & train
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
# sess생성 & variable 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 30001):
    _, cost_val = sess.run([train, cost], feed_dict={X:scaled_X_data,
                                                     y:scaled_y_data})
    if step%5000==1:
        print(f'{step}번째 cost : {cost_val}')
print(f'최종 {step}번째 cost : {cost_val}')

1번째 cost : 3.786799669265747
5001번째 cost : 0.0002803198585752398
10001번째 cost : 0.0002685599902179092
15001번째 cost : 0.0002610703813843429
20001번째 cost : 0.0002562982263043523
25001번째 cost : 0.00025325961178168654
최종 30000번째 cost : 0.0002513229555916041


In [63]:
# 예측
input_data = np.array([[72,79,74],
                       [92,87,92]])
scaled_input_data = scaler_x.transform(input_data)
print('scale조정된 입력값 : \n',scaled_input_data)
hat = sess.run(H, feed_dict={X : scaled_input_data})
predict_data = scaler_y.inverse_transform(hat)
print('예측 점수 :\n', predict_data)

scale조정된 입력값 : 
 [[-1.29458143 -0.51154887 -1.02755507]
 [ 0.72820205  0.21923523  0.56692694]]
예측 점수 :
 [[149.75903]
 [182.5394 ]]


In [64]:
input_data = [[90,85,90]]
hat = sess.run(H, feed_dict={X : scaler_x.transform(input_data)})
scaler_y.inverse_transform(hat)

array([[178.60753]], dtype=float32)